#!/usr/bin/env bash
set -euo pipefail

EXPERIMENT="${EXPERIMENT:-deepseek}"
ROOT="/u/mjha1/Proof2Silicon/journal_phase"
CODEBASE="$ROOT/CODEBASE"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

export SLM_MODEL_NAME="${SLM_MODEL_NAME:-Qwen/Qwen3-1.7B}"
export DAFNY_JUDGE_PROVIDER="openai"
export DAFNY_JUDGE_MODEL="${DAFNY_JUDGE_MODEL:-gpt-5.4}"
export DAFNY_JUDGE_REASONING="${DAFNY_JUDGE_REASONING:-high}"
export DAFNY_JUDGE_MAX_TOKENS="${DAFNY_JUDGE_MAX_TOKENS:-1024}"
export OPENAI_GENERATOR_MODEL="${OPENAI_GENERATOR_MODEL:-gpt-5.4-mini}"
export OPENAI_GENERATOR_REASONING="${OPENAI_GENERATOR_REASONING:-medium}"
export DEEPSEEK_GENERATOR_MODEL="${DEEPSEEK_GENERATOR_MODEL:-deepseek-chat}"
export HF_GENERATOR_MODEL="${HF_GENERATOR_MODEL:-Qwen/Qwen3-Coder-30B-A3B-Instruct:cheapest}"
export DAFNY_MIXED_SEED="${DAFNY_MIXED_SEED:-20260802}"
export DAFNY_MIXED_GENERATORS="deepseek,openai,qwen_hf"

case "$EXPERIMENT" in
  deepseek|openai|qwen_hf|mixed)
    export DAFNY_GENERATOR_MODE="$EXPERIMENT"
    ;;
  *)
    echo "Unknown EXPERIMENT=$EXPERIMENT" >&2
    exit 2
    ;;
esac

RUN_NAME="journal_${EXPERIMENT}_${TIMESTAMP}"
export WANDB_RUN_NAME="$RUN_NAME"
export WANDB_RUN_ID="p2s_${EXPERIMENT}_${TIMESTAMP}"
export PROOF2SILICON_EXPERIMENT="$EXPERIMENT"
export PROOF2SILICON_RUN_DIR="$ROOT/journal_runs/$RUN_NAME"
CHECKPOINT="$PROOF2SILICON_RUN_DIR/checkpoints/final_model.pt"
mkdir -p "$PROOF2SILICON_RUN_DIR/checkpoints"

python "$CODEBASE/preflight_models.py"

cat > "$PROOF2SILICON_RUN_DIR/config.env" <<EOF
EXPERIMENT=$EXPERIMENT
SLM_MODEL_NAME=$SLM_MODEL_NAME
DAFNY_GENERATOR_MODE=$DAFNY_GENERATOR_MODE
DEEPSEEK_GENERATOR_MODEL=$DEEPSEEK_GENERATOR_MODEL
OPENAI_GENERATOR_MODEL=$OPENAI_GENERATOR_MODEL
OPENAI_GENERATOR_REASONING=$OPENAI_GENERATOR_REASONING
HF_GENERATOR_MODEL=$HF_GENERATOR_MODEL
DAFNY_JUDGE_MODEL=$DAFNY_JUDGE_MODEL
DAFNY_JUDGE_REASONING=$DAFNY_JUDGE_REASONING
DAFNY_MIXED_SEED=$DAFNY_MIXED_SEED
EOF

cd "$CODEBASE"
python journal_main.py \
  --checkpoint "$CHECKPOINT" \
  --start_epoch 0 \
  --num_epochs 5 \
  "$@" 2>&1 | tee "$PROOF2SILICON_RUN_DIR/training.log"
