_wandb:
    value:
        cli_version: 0.25.0
        e:
            fms0p94y4h8s5hm8e8r0uuwt1n3vb7go:
                args:
                    - --start_epoch
                    - "0"
                    - --wandb_project
                    - dafny-rl_full
                    - --wandb_entity
                    - drprofmjha-university-of-illinois-urbana-champaign
                    - --max_workers
                    - "1"
                codePath: journal_phase/CODEBASE/main.py
                codePathLocal: main.py
                cpu_count: 288
                cpu_count_logical: 288
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "256654442496"
                        used: "22886612992"
                email: drprofmjha@gmail.com
                executable: /u/mjha1/rl_env311/bin/python
                git:
                    commit: 0a10948748bed4ab42ca076861322affea199fe9
                    remote: git@github.com:Severus-Matthew/Proof2Silicon.git
                gpu: NVIDIA GH200 120GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-50867179-5a5c-934c-05b7-595f4cba1c5d
                host: gh058.hsn.cm.delta.internal.ncsa.edu
                memory:
                    total: "921330843648"
                os: Linux-6.4.0-150600.23.53-64kb-aarch64-with-glibc2.38
                program: /u/mjha1/Proof2Silicon/journal_phase/CODEBASE/main.py
                python: CPython 3.12.9
                root: /u/mjha1/Proof2Silicon/journal_phase/CODEBASE
                slurm:
                    cluster_name: delta-gh
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "6"
                    cpus_per_task: "6"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: bgrm-dtai-gh
                    job_cpus_per_node: 6(x2)
                    job_end_time: "1775668946"
                    job_gid: "202"
                    job_gpus: "0"
                    job_id: "2083731"
                    job_name: dafny_full
                    job_nodelist: gh[058,107]
                    job_num_nodes: "2"
                    job_partition: ghx4
                    job_qos: bgrm-dtai-gh
                    job_start_time: "1775496146"
                    job_uid: "71799"
                    job_user: mjha1
                    jobid: "2083731"
                    localid: "0"
                    nnodes: "2"
                    nodeid: "0"
                    nodelist: gh[058,107]
                    nprocs: "2"
                    ntasks: "2"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /u/mjha1
                    submit_host: gh-login02.delta.ncsa.illinois.edu
                    task_pid: "2903889"
                    tasks_per_node: 1(x2)
                    topology_addr: deltaai_fabric.chassis_x8102c1.gh058
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=6
                startedAt: "2026-04-06T17:22:56.362654Z"
                writerId: fms0p94y4h8s5hm8e8r0uuwt1n3vb7go
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 98
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.25.0
            "6": 5.5.0
            "12": 0.25.0
            "13": linux-aarch64
checkpoint:
    value: /u/mjha1/Proof2Silicon/journal_phase/checkpoints/run_CHK/final_model_new.pt
max_workers:
    value: 1
start_epoch:
    value: 0
temperature:
    value: 0.75
wandb_entity:
    value: drprofmjha-university-of-illinois-urbana-champaign
wandb_project:
    value: dafny-rl_full
